# Generated by Django 3.2.16 on 2023-01-30 13:28

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogap', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=7000, null=True),
        ),
    ]
