# Generated by Django 3.2.16 on 2023-01-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogap', '0005_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default='false', verbose_name='Approved'),
        ),
    ]
