# Generated by Django 3.2.16 on 2023-02-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogap', '0006_alter_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default='False', verbose_name='Approved'),
        ),
    ]
