# Generated by Django 3.2.16 on 2023-02-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogap', '0011_alter_comment_no_of_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='no_of_comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='no_of_likes',
            field=models.ManyToManyField(related_name='blogap_no_of_likes', to='blogap.Post'),
        ),
    ]
