# Generated by Django 3.2.16 on 2023-02-03 00:51

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogap', '0013_auto_20230202_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_of_comment', models.DateTimeField(auto_now_add=True)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=7000, null=True)),
                ('approved', models.BooleanField(default='False', verbose_name='Approved')),
                ('contributor_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blogap.post')),
                ('no_of_likes', models.ManyToManyField(related_name='blogap_no_of_likes', to='blogap.Post')),
            ],
        ),
        migrations.DeleteModel(
            name='AddComment',
        ),
    ]
