# Generated by Django 3.2.16 on 2023-02-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogap', '0018_comment_cname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cname',
        ),
    ]
