# Generated by Django 3.2.16 on 2023-02-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogap', '0019_remove_comment_cname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
